trigger: 
  - main
  - feature*

variables:
  - name: AZSUBSCRIPTION  
    value: AzCloud
  - name: Deploy
    value: false  
  - name: AgentPool
    value: Victory
  - name: DeployEnvironment
    value: VictoryDev  
stages:
  - stage: BuildApp 
    condition: always()
    jobs:
    - job: BuildWar    
      workspace:
        clean: all
      pool:
        name: $(AgentPool)
      steps:    
      - task: Bash@3
        inputs:
          targetType: 'filePath'
          filePath: deployscripts/buildJob.sh
        env:
          buildNumber: $(Build.BuildNumber)
          buildDir: $(Pipeline.Workspace) 
      - task: CopyFiles@2
        displayName: 'Copy Files to artifact directory'
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          Contents: '**/target/*.?(war|jar)'
          TargetFolder: $(Build.ArtifactStagingDirectory)
      - upload: $(Build.ArtifactStagingDirectory)
        artifact: petclinic
    
  - stage: deployToDev
    pool:
      name: $(AgentPool)      
    condition: and(succeeded(), eq(variables.Deploy, 'true'))
    jobs: 
      - deployment: VMDeploy
        displayName: Deploy to Dev Web
        environment:
          name: $(DeployEnvironment)
          resourceType: VirtualMachine
        strategy:
          runOnce:            
            preDeploy:
              steps:
              - download: current
                artifact: petclinic
              - script: echo "Starting Deployment"
            deploy:
              steps:
              - task: Bash@3
                inputs:
                  targetType: 'inline'
                  script: |

                    # Modify deployment script based on the app type
                    echo "Starting deployment script run"
                    sudo cp $(Pipeline.Workspace)/petclinic/target/*.war /opt/tomcat/webapps/petclinic.war 

