---
apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    app: sqldb
spec:
  containers:
  - name: database
    image: mysql:5.7
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: 'petclinic'
      - name: MYSQL_USER
        value: petclinic
      - name: MYSQL_PASSWORD
        value: petclinic 
      - name: MYSQL_DATABASE
        value: petclinic 
    resources:
      requests:
        memory: "128Mi"
        cpu: "200m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    ports:
      - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mydb
spec:
  selector:
    app: sqldb
  ports:
  - port: 3306
    targetPort: 3306

  