name: SpringApp CI-CD
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - "development"
      
  pull_request:
    branches: 
      - "development"

jobs:
  buildApp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2      

      - name: Build with maven
        run: mvn clean package

      - name: Upload Artifacts
        id: upload_artifact
        uses: actions/upload-artifact@v3
        with:
          name: petclinic_${{ github.run_number}}.war
          path: target/petclinic.war