name: SpringApp CI-CD
run-name: Build & Deploy Springboot App  🚀
on: 
  push:
    branches:
      - "development"
      

jobs:
  buildApp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2      

      - name: Build with maven
        run: mvn clean package

      - name: Upload Artifacts
        id: upload_artifact
        uses: actions/upload-artifact@v3
        with:
          name: petclinic_${{ github.run_number}}.war
          path: target/petclinic.war
          retention-days: 2
      
      # Docker Login
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


     # Build & Push docekr iamge

    
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: kbaddi/petclinic:${{github.run_number}}